Importing Libraries

In [ ]:
import pandas as pd ## Data Manipulation
import numpy as np ## Mathematical Calculations

Data Ingestion

In [11]:
data_path="/content/drive/MyDrive/1782321019230_Patient_Readmission.xlsx"

df=pd.read_excel(data_path)

display(df)

,Patient ID,Age,Gender,Admission Type,Length of Stay,Number of Diagnoses,Blood Pressure,Blood Sugar Levels,Previous Admissions,Readmission
0,1,62,Female,Elective,4,5,110,130,1,No
1,2,65,Male,Emergency,19,2,157,81,4,No
2,3,82,Female,Emergency,18,4,74,84,0,No
3,4,85,Male,Emergency,2,4,106,85,4,No
4,5,85,Female,Elective,19,3,80,119,3,No
...,...,...,...,...,...,...,...,...,...,...
2995,2996,50,Female,Emergency,4,2,150,143,0,No
2996,2997,21,Female,Elective,1,2,141,169,1,No
2997,2998,20,Female,Elective,2,8,155,180,3,No
2998,2999,69,Female,Elective,13,9,117,173,4,Yes
2999,3000,45,Female,Elective,26,7,108,84,0,No

In [12]:
#Checking the information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Patient ID           3000 non-null   int64
 1   Age                  3000 non-null   int64
 2   Gender               3000 non-null   object
 3   Admission Type       3000 non-null   object
 4   Length of Stay       3000 non-null   int64
 5   Number of Diagnoses  3000 non-null   int64
 6   Blood Pressure       3000 non-null   int64
 7   Blood Sugar Levels   3000 non-null   int64
 8   Previous Admissions  3000 non-null   int64
 9   Readmission          3000 non-null   object
dtypes: int64(7), object(3)
memory usage: 234.5+ KB

Observation

The dataset consists 3000 patient records and 10 columns. There are no missing values and non null entries. It contains a mix of numerical and categorical variables.

In [20]:
# Count the number of duplicate rows
df.duplicated().sum()

np.int64(0)

Observation

No duplicates in the dataset

In [17]:
# Display summary statistics for categorical columns
df.describe(include='object')

       Gender Admission Type Readmission
count    3000           3000        3000
unique      2              2           2
top      Male       Elective          No
freq     1555           1563        2134

Observation

The gender column contains two unique categories and male being the most frequent. Elective being the most common admission type and has No readmission records.

In [18]:
# Count the number of patients by gender
df['Gender'].value_counts()

Gender
Male      1555
Female    1445
Name: count, dtype: int64

Observation

More male patients than female patients

In [ ]:
# Checking the age buckets
conditions = [
    df['Age'] < 25,
    df['Age'] .between (25, 40),
    df['Age'] .between (41, 60),
    df['Age'] .between (61, 80),
    df['Age'] > 80

]
choices = [
    'Youth',
    'Young Adults',
    'Adults',
    'Senior',
    'Old'

]
df['Age Group'] = np.select(conditions ,choices, default='Unknown')

In [ ]:
# count patients per age group
df['Age Group'].value_counts()

Observation

Seniors make up the largest age group in the dataset 835 patients, followed by Adults 824 patients.

In [ ]:
# Checking the age groups by Admission Type (Emergency vs Elective)
pd.crosstab(df['Admission Type'], df['Age Group'])

Observation

There are fewer emergency patients in each age group than elective patients.